version: '3.7'
services:
  main-python:
    image: "dockerfile-crawler"
    volumes:
     - .:/crawler_app

  mongodb:
    image: "mongo:latest"
    links:
      - main-python
    volumes: 
      - ./db:/data/db
    ports:
      - "27017:27017"